# Manage Git hooks with Lefthook
# https://evilmartians.com/chronicles/lefthook-knock-your-teams-code-back-into-shape
# https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md

pre-commit:
  parallel: true
  commands:
    prettier:
      glob: '*.{html,json,md,scss,xml,yml}'
      run: npx prettier --write {staged_files}
      stage_fixed: true
    stylelint:
      glob: '*.{scss}'
      run: npx stylelint {staged_files}
      stage_fixed: true
